# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mv/Downloads/lab4-20211014T204009Z-001/lab4/lab5_3_1/lab5_3_1.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci
# IP: The module: 'c_counter_binary_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mv/Downloads/lab4-20211014T204009Z-001/lab4/lab5_3_1/lab5_3_1.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/mv/Downloads/lab4-20211014T204009Z-001/lab4/lab5_3_1/lab5_3_1.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci
# IP: The module: 'c_counter_binary_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mv/Downloads/lab4-20211014T204009Z-001/lab4/lab5_3_1/lab5_3_1.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
