# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mv/Documents/dsde/lab5/lab5_5_3/lab5_5_3.srcs/sources_1/ip/eight_bit_counter/eight_bit_counter.xci
# IP: The module: 'eight_bit_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mv/Documents/dsde/lab5/lab5_5_3/lab5_5_3.srcs/sources_1/ip/eight_bit_counter/eight_bit_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eight_bit_counter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/mv/Documents/dsde/lab5/lab5_5_3/lab5_5_3.srcs/sources_1/ip/eight_bit_counter/eight_bit_counter.xci
# IP: The module: 'eight_bit_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mv/Documents/dsde/lab5/lab5_5_3/lab5_5_3.srcs/sources_1/ip/eight_bit_counter/eight_bit_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eight_bit_counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
