# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mv/Documents/DSED/Digital_Electronic_Design/lab5/lab5_5_1/lab5_5_1.srcs/sources_1/ip/clk_wiz_5_1/clk_wiz_5_1.xci
# IP: The module: 'clk_wiz_5_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mv/Documents/DSED/Digital_Electronic_Design/lab5/lab5_5_1/lab5_5_1.srcs/sources_1/ip/clk_wiz_5_1/clk_wiz_5_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/mv/Documents/DSED/Digital_Electronic_Design/lab5/lab5_5_1/lab5_5_1.srcs/sources_1/ip/clk_wiz_5_1/clk_wiz_5_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/mv/Documents/DSED/Digital_Electronic_Design/lab5/lab5_5_1/lab5_5_1.srcs/sources_1/ip/clk_wiz_5_1/clk_wiz_5_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/mv/Documents/DSED/Digital_Electronic_Design/lab5/lab5_5_1/lab5_5_1.srcs/sources_1/ip/clk_wiz_5_1/clk_wiz_5_1.xci
# IP: The module: 'clk_wiz_5_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mv/Documents/DSED/Digital_Electronic_Design/lab5/lab5_5_1/lab5_5_1.srcs/sources_1/ip/clk_wiz_5_1/clk_wiz_5_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/mv/Documents/DSED/Digital_Electronic_Design/lab5/lab5_5_1/lab5_5_1.srcs/sources_1/ip/clk_wiz_5_1/clk_wiz_5_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/mv/Documents/DSED/Digital_Electronic_Design/lab5/lab5_5_1/lab5_5_1.srcs/sources_1/ip/clk_wiz_5_1/clk_wiz_5_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
