# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.cache/wt [current_project]
set_property parent.project_path E:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo e:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib E:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.srcs/sources_1/new/one_second_pulse.vhd
read_ip -quiet e:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.srcs/sources_1/ip/clk_5MHz/clk_5MHz.xci
set_property used_in_implementation false [get_files -all e:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.srcs/sources_1/ip/clk_5MHz/clk_5MHz_board.xdc]
set_property used_in_implementation false [get_files -all e:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.srcs/sources_1/ip/clk_5MHz/clk_5MHz.xdc]
set_property used_in_implementation false [get_files -all e:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.srcs/sources_1/ip/clk_5MHz/clk_5MHz_ooc.xdc]
set_property is_locked true [get_files e:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.srcs/sources_1/ip/clk_5MHz/clk_5MHz.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.srcs/constrs_1/imports/DSED_Group6/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files E:/DSED/DSED_Group6/lab4_2_1/lab5/lab5.srcs/constrs_1/imports/DSED_Group6/Nexys4DDR_Master.xdc]


synth_design -top one_second_pulse -part xc7a100tcsg324-1


write_checkpoint -force -noxdef one_second_pulse.dcp

catch { report_utilization -file one_second_pulse_utilization_synth.rpt -pb one_second_pulse_utilization_synth.pb }
