# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/dsed_audio/Nexys4DDR_Master.xdc

# IP: ip/clk_wiz_12/clk_wiz_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_12 || ORIG_REF_NAME==clk_wiz_12}]
