# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dsed/DSED_6/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12megas/clk_12megas.xci
# IP: The module: 'clk_12megas' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dsed/DSED_6/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12megas/clk_12megas_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12megas'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/dsed/DSED_6/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12megas/clk_12megas.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12megas'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/dsed/DSED_6/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12megas/clk_12megas_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12megas'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/dsed/DSED_6/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12megas/clk_12megas.xci
# IP: The module: 'clk_12megas' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dsed/DSED_6/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12megas/clk_12megas_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12megas'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/dsed/DSED_6/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12megas/clk_12megas.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12megas'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/dsed/DSED_6/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12megas/clk_12megas_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12megas'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
